In [9]:
import pandas as pd
import numpy as np
import math

df=pd.read_csv('mpipe.csv')
df

,epoch_time,ls_x,ls_y,ls_z,le_x,le_y,le_z,lw_x,lw_y,lw_z,...,rs_z,re_x,re_y,re_z,rw_x,rw_y,rw_z,tr_x,tr_y,tr_z
0,1.686732e+09,0.2175,-0.5380,2.480,0.1888,-0.3079,2.492,0.3220,-0.11940,3.215,...,2.440,0.2964,-0.14690,2.562,0.5283,-0.007950,2.543,0.2090,-0.4116,2.451
1,1.686732e+09,0.2051,-0.5366,2.463,0.1930,-0.3074,2.492,0.3237,-0.12280,3.215,...,2.445,0.2983,-0.14660,2.562,0.5320,-0.005135,2.535,0.1973,-0.4124,2.451
2,1.686732e+09,0.1942,-0.5396,2.463,0.1948,-0.3060,2.492,0.3276,-0.12494,3.215,...,2.463,0.2950,-0.14890,2.562,0.5312,-0.002335,2.530,0.1920,-0.4238,2.451
3,1.686732e+09,0.1884,-0.5570,2.457,0.1934,-0.3118,2.492,0.3306,-0.12195,3.215,...,2.463,0.2742,-0.14670,2.562,0.5005,-0.002335,2.530,0.1808,-0.4275,2.451
4,1.686732e+09,0.1843,-0.5854,2.475,0.2021,-0.3180,2.492,0.4375,-0.18350,3.215,...,2.445,0.2190,-0.16320,2.562,0.4410,-0.013450,2.523,0.1744,-0.4558,2.451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,1.686732e+09,0.2664,-0.5180,2.475,0.0000,-0.0000,2.492,0.5664,-0.10030,3.215,...,2.480,0.2893,-0.11847,2.512,0.5320,-0.005188,2.562,0.2274,-0.4233,2.451
121,1.686732e+09,0.2712,-0.5110,2.475,0.0000,-0.0000,2.492,0.5680,-0.08780,3.215,...,2.475,0.2930,-0.11884,2.518,0.5405,-0.002377,2.574,0.2317,-0.4160,2.451
122,1.686732e+09,0.2664,-0.5180,2.475,0.4111,-0.3176,2.492,0.5650,-0.08130,3.215,...,2.469,0.2878,-0.12067,2.498,0.5320,-0.002377,2.523,0.2329,-0.4207,2.451
123,1.686732e+09,0.2705,-0.5264,2.475,0.3296,-0.2646,2.492,0.5566,-0.09690,3.215,...,2.492,0.2870,-0.11760,2.492,0.5293,-0.005135,2.535,0.2340,-0.4255,2.451
124,1.686732e+09,0.2642,-0.5273,2.475,0.0000,-0.0000,2.492,0.5117,-0.09625,3.215,...,2.469,0.2886,-0.12100,2.506,0.5360,-0.005200,2.568,0.2334,-0.4216,2.451

In [10]:
import numpy as np
xyz=['x','y','z']
ls,le,lw,rs,re,rw=[],[],[],[],[],[]

c=1
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])   
        point=np.array(point)      
        ls.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])  
        point=np.array(point)      
        le.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        lw.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        rs.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        re.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        rw.append(point)

ls=np.array(ls)
le=np.array(le)
lw=np.array(lw)

rs=np.array(rs) 
re=np.array(re)
rw=np.array(rw)

In [11]:
import numpy as n
lu=list(ls-le)
ll=list(le-lw)
ru=list(rs-re)
rl=list(re-rw)
ss=list(rs-ls)

for i in range(len(lu)):
    lu[i]=np.linalg.norm(lu[i])
    ll[i]=np.linalg.norm(ll[i])
    ru[i]=np.linalg.norm(ru[i])
    rl[i]=np.linalg.norm(rl[i])
    ss[i]=np.linalg.norm(ss[i])

In [12]:
df_ll=pd.DataFrame(columns=['lu','ll','ru','rl','ss'])

df_ll['lu']=pd.Series(lu)
df_ll['ll']=pd.Series(ll)
df_ll['ru']=pd.Series(ru)
df_ll['rl']=pd.Series(rl)
df_ll['ss']=pd.Series(ss)

df_ll.to_csv('limbl.csv',index=False)

In [13]:
df_ll.agg(
    {
        "lu": ["min", "max", "median", "mean"],
        "ll": ["min", "max", "median", "mean"],
        "ru": ["min", "max", "median", "mean"],
        "rl": ["min", "max", "median", "mean"],
        "ss": ["min", "max", "median", "mean"],
    }
)

              lu        ll        ru        rl        ss
min     0.226802  0.258877  0.223747  0.098485  0.053889
max     0.590030  0.923904  0.363564  2.585845  0.405494
median  0.298699  0.288439  0.299405  0.275734  0.371939
mean    0.301237  0.368829  0.293339  0.293187  0.317292

In [14]:
df_ll.idxmax()

lu    124
ll    120
ru    120
rl    112
ss     21
dtype: int64

In [15]:
df_ll.idxmin()

lu    116
ll     16
ru     93
rl     36
ss    113
dtype: int64

In [16]:
df_ll.std()

lu    0.053817
ll    0.180692
ru    0.033441
rl    0.210061
ss    0.110934
dtype: float64