In [9]:
# Reading the Landmarks csv file
import pandas as pd
import numpy as np
import math

df=pd.read_csv('mpipe.csv')
df

,epoch_time,ls_x,ls_y,ls_z,le_x,le_y,le_z,lw_x,lw_y,lw_z,...,rs_z,re_x,re_y,re_z,rw_x,rw_y,rw_z,tr_x,tr_y,tr_z
0,1.685773e+09,-0.07980,-0.2896,1.438,-0.04790,0.00679,1.481,-0.02133,0.2986,1.448,...,1.381,-0.4368,0.03833,1.440,-0.4377,0.3145,1.398,-0.2360,-0.2367,1.379
1,1.685773e+09,-0.07840,-0.2888,1.442,-0.04828,0.01177,1.492,-0.02121,0.2969,1.440,...,1.379,-0.4353,0.03806,1.430,-0.4316,0.3098,1.378,-0.2360,-0.2367,1.379
2,1.685773e+09,-0.07830,-0.2883,1.440,-0.04790,0.01331,1.481,-0.02121,0.2952,1.440,...,1.385,-0.4353,0.03964,1.430,-0.4310,0.3093,1.376,-0.2351,-0.2344,1.374
3,1.685773e+09,-0.07806,-0.2876,1.436,-0.04807,0.01500,1.486,-0.02133,0.2969,1.448,...,1.381,-0.4358,0.03967,1.432,-0.4316,0.3096,1.383,-0.2355,-0.2362,1.376
4,1.685773e+09,-0.07684,-0.2888,1.442,-0.04828,0.01834,1.492,-0.02283,0.2942,1.442,...,1.376,-0.4355,0.04422,1.426,-0.4287,0.3074,1.374,-0.2355,-0.2346,1.376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,1.685773e+09,-0.17330,-0.2908,1.376,-0.12630,0.01756,1.428,-0.08344,0.2870,1.393,...,1.283,-0.5330,0.05862,1.359,-0.5005,0.3262,1.327,-0.3257,-0.2236,1.278
492,1.685773e+09,-0.17290,-0.2898,1.372,-0.13010,0.01762,1.434,-0.08320,0.2864,1.389,...,1.276,-0.5260,0.05762,1.336,-0.4995,0.3237,1.317,-0.3280,-0.2241,1.281
493,1.685773e+09,-0.17150,-0.2903,1.374,-0.12980,0.02074,1.430,-0.08514,0.2878,1.396,...,1.278,-0.5337,0.05850,1.356,-0.5005,0.3225,1.312,-0.3264,-0.2241,1.281
494,1.685773e+09,-0.17050,-0.2913,1.378,-0.13150,0.02077,1.432,-0.08527,0.2880,1.398,...,1.275,-0.5327,0.05840,1.354,-0.4993,0.3218,1.309,-0.3276,-0.2250,1.286
495,1.685773e+09,-0.17110,-0.2908,1.383,-0.13210,0.02243,1.438,-0.08500,0.2874,1.394,...,1.271,-0.5312,0.05990,1.354,-0.4973,0.3210,1.300,-0.3270,-0.2255,1.289

In [10]:
# Saving the 3D points of each landmark
xyz=['x','y','z']
ls,le,lw,rs,re,rw=[],[],[],[],[],[]

c=1
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])   
        point=np.array(point)      
        ls.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])  
        point=np.array(point)      
        le.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        lw.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        rs.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        re.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        rw.append(point)

# Converting to numpy arrays
ls=np.array(ls)
le=np.array(le)
lw=np.array(lw)

rs=np.array(rs) 
re=np.array(re)
rw=np.array(rw)

In [11]:
# Finding the distances between the landmarks
lu=list(ls-le) # Left upper arm
ll=list(le-lw) # Left lower arm
ru=list(rs-re) # Rigth upper arm
rl=list(re-rw) # Right lower arm
ss=list(rs-ls) # Biacromial length / distance between shoulder

for i in range(len(lu)):
    lu[i]=np.linalg.norm(lu[i])
    ll[i]=np.linalg.norm(ll[i])
    ru[i]=np.linalg.norm(ru[i])
    rl[i]=np.linalg.norm(rl[i])
    ss[i]=np.linalg.norm(ss[i])

In [12]:
# Saving the values in a dataframe and exporting to csv
df_ll=pd.DataFrame(columns=['lu','ll','ru','rl','ss'])

df_ll['lu']=pd.Series(lu)
df_ll['ll']=pd.Series(ll)
df_ll['ru']=pd.Series(ru)
df_ll['rl']=pd.Series(rl)
df_ll['ss']=pd.Series(ss)

df_ll.to_csv('limbl.csv',index=False)

In [13]:
df_ll.agg(
    {
        "lu": ["min", "max", "median", "mean"],
        "ll": ["min", "max", "median", "mean"],
        "ru": ["min", "max", "median", "mean"],
        "rl": ["min", "max", "median", "mean"],
        "ss": ["min", "max", "median", "mean"],
    }
)

              lu        ll        ru        rl        ss
min     0.244419  0.203278  0.276433  0.069509  0.320858
max     0.324694  1.473227  0.476516  1.151856  0.350020
median  0.307542  0.273866  0.318107  0.269278  0.331895
mean    0.302580  0.277450  0.321963  0.271564  0.332358

In [14]:
df_ll.idxmax()

lu    354
ll    165
ru    291
rl    248
ss    144
dtype: int64

In [15]:
df_ll.idxmin()

lu    408
ll    409
ru    408
rl    300
ss    329
dtype: int64

In [16]:
df_ll.std()

lu    0.014362
ll    0.076478
ru    0.028559
rl    0.078003
ss    0.005100
dtype: float64