In [11]:
import pandas as pd
import numpy as np
import math

df=pd.read_csv('mpipe.csv')
df

,epoch_time,LH_x,LH_y,LH_z,LK_x,LK_y,LK_z,LA_x,LA_y,LA_z,...,RH_z,RK_x,RK_y,RK_z,RA_x,RA_y,RA_z,RT_x,RT_y,RT_z
0,1.686721e+09,-0.13840,-0.031280,2.398,-0.074000,0.3677,2.756,-0.013580,0.7324,2.816,...,2.486,-0.2070,0.4773,2.562,-0.3064,0.8804,2.568,-0.2751,0.9385,2.440
1,1.686721e+09,-0.10030,-0.027620,2.312,-0.001148,0.3699,2.748,-0.013540,0.7305,2.809,...,2.371,-0.2476,0.4580,2.486,-0.3047,0.8670,2.530,-0.2670,0.9330,2.440
2,1.686721e+09,-0.09705,-0.018250,2.422,-0.001119,0.3984,2.676,-0.013770,0.7490,2.855,...,2.246,-0.2750,0.4634,2.486,-0.3076,0.8613,2.530,-0.2860,0.9375,2.486
3,1.686721e+09,-0.09656,-0.010190,2.410,-0.010150,0.4119,2.727,-0.013620,0.7534,2.824,...,2.361,-0.2905,0.4622,2.480,-0.3040,0.8623,2.523,-0.2742,0.9380,2.480
4,1.686721e+09,-0.09590,-0.002210,2.395,-0.016020,0.4026,2.703,-0.013580,0.7480,2.816,...,2.383,-0.2979,0.4540,2.451,-0.3083,0.8496,2.535,-0.2764,0.9180,2.428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,1.686721e+09,-0.09610,-0.006930,2.217,-0.079350,0.4473,2.371,-0.095100,0.8660,2.512,...,2.232,-0.3113,0.4502,2.389,-0.2957,0.8790,2.523,NaN,NaN,NaN
158,1.686721e+09,-0.09534,-0.004566,2.256,0.020810,0.6265,3.361,-0.001119,0.9110,2.676,...,2.277,-0.2778,0.4578,2.371,-0.2803,0.8633,2.486,NaN,NaN,NaN
159,1.686721e+09,-0.08203,-0.002060,2.232,0.045300,0.4348,2.334,0.043520,0.8096,2.377,...,2.193,-0.2556,0.4590,2.312,-0.2840,0.8857,2.543,NaN,NaN,NaN
160,1.686721e+09,0.01073,0.025910,2.107,0.129600,0.4460,2.422,0.132700,0.7812,2.428,...,2.207,-0.1971,0.4717,2.312,-0.2832,0.8830,2.512,NaN,NaN,NaN
161,1.686721e+09,0.01920,0.053300,2.287,0.128400,0.4417,2.398,0.149400,0.7880,2.440,...,2.217,-0.1769,0.4653,2.281,-0.2837,0.8870,2.492,NaN,NaN,NaN

In [12]:
import numpy as np
LH, LK, LA, LT, RH, RK, RA, RT = [],[],[],[],[],[],[],[]

c=1
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])   
        point=np.array(point)      
        LH.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        LK.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        LA.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        LT.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])  
        point=np.array(point)      
        RH.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        RK.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        RA.append(point)
c+=3
for i,j in df.iterrows():
    for k in range(c,c+3,3):
        point=[]
        for p in range(k,k+3):
            point.append(j[p])
        point=np.array(point)        
        RT.append(point)

LH=np.array(LH)
LK=np.array(LK)
LA=np.array(LA)
LT=np.array(LT)

RH=np.array(RH)
RK=np.array(RK)
RA=np.array(RA)
RT=np.array(RT)

In [13]:
Lul=list(LH-LK)
Lll=list(LK-LA)
Lf=list(LA-LT)
Rul=list(RH-RK)
Rll=list(RK-RA)
Rf=list(RA-RT)
H=list(RH-LH)

for i in range(len(Lul)):
    Lul[i]=np.linalg.norm(Lul[i])
    Lll[i]=np.linalg.norm(Lll[i])
    Lf[i]=np.linalg.norm(Lf[i])
    Rul[i]=np.linalg.norm(Rul[i])
    Rll[i]=np.linalg.norm(Rll[i])
    Rf[i]=np.linalg.norm(Rf[i])
    H[i]=np.linalg.norm(H[i])

In [14]:
df_ll=pd.DataFrame(columns=['Lul','Lll','Lf','Rul','Rll','Rf','H'])

df_ll['Lul']=pd.Series(Lul)
df_ll['Lll']=pd.Series(Lll)
df_ll['Lf']=pd.Series(Lf)
df_ll['Rul']=pd.Series(Rul)
df_ll['Rll']=pd.Series(Rll)
df_ll['Rf']=pd.Series(Rf)
df_ll['H']=pd.Series(H)

df_ll.to_csv('limbl.csv',index=False)

In [15]:
df_ll.agg(
    {
        "Lul": ["min", "max", "median", "mean"],
        "Lll": ["min", "max", "median", "mean"],
        "Lf": ["min", "max", "median", "mean"],
        "Rul": ["min", "max", "median", "mean"],
        "Rll": ["min", "max", "median", "mean"],
        "Rf": ["min", "max", "median", "mean"],
        "H": ["min", "max", "median", "mean"],
    }
)

             Lul       Lll        Lf       Rul       Rll        Rf         H
min     0.396755  0.335268  0.168952  0.363095  0.360231  0.090604  0.108354
max     1.277795  0.742055  0.467680  0.603796  0.486046  2.690664  0.237945
median  0.442815  0.450681  0.210244  0.465144  0.425266  0.158500  0.218961
mean    0.454894  0.445737  0.245029  0.455711  0.426743  0.241996  0.216155

In [16]:
df_ll.idxmax()

Lul    158
Lll    158
Lf      15
Rul    152
Rll    159
Rf      48
H       82
dtype: int64

In [17]:
df_ll.idxmin()

Lul     10
Lll    160
Lf      12
Rul    146
Rll    131
Rf       2
H        1
dtype: int64

In [18]:
df_ll.std()

Lul    0.070461
Lll    0.037073
Lf     0.094794
Rul    0.035819
Rll    0.023050
Rf     0.325538
H      0.017874
dtype: float64